---

- hosts: all

  tasks:



  - name: copy Dockerfile into Remote machine

    copy:

      src: Dockerfile

      dest: .

  - name: copy war file into Remote machine

    copy:

      src: index.html

      dest: .

  - name: Stop the running container

    command: sudo docker stop customcontainer

    ignore_errors: True



  - name: remove the running container

    command: sudo docker rm customcontainer

    ignore_errors: True



  - name: remove the running image

    command: sudo docker rmi customimage

    ignore_errors: True



  - name: Create the image from Docker file

    command: sudo docker build -t customimage .



  - name: Create and run container

    command: sudo docker run -d -p 8080:8080 --name customcontainer customimage
